FROM python:3.11

# Устанавливаем рабочую директорию
WORKDIR /taskproject

# Устанавливаем переменные окружения
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Устанавливаем зависимости
COPY requirements.txt /taskproject/
RUN pip install --no-cache-dir -r requirements.txt

# Копируем проект
COPY . /taskproject